parameters:
    pi_app_admin.validator.unique.class: PiApp\AdminBundle\Validator\Constraints\UniqueValidator
    pi_app_admin.validator.collectionof.class: PiApp\AdminBundle\Validator\Constraints\CollectionOfValidator
    pi_app_admin.validator.partner.class: PiApp\AdminBundle\Validator\Constraints\MaxEntitiesByQueryValidator

services:
    pi_app_admin.validator.unique:
       class:      %pi_app_admin.validator.unique.class%
       arguments: [@service_container]
       tags:
            - { name: validator.constraint_validator, alias: pi_app_admin.validator.unique }
            
    pi_app_admin.validator.collectionof:
       class:      %pi_app_admin.validator.collectionof.class%
       tags:
            - { name: validator.constraint_validator, alias: pi_app_admin.validator.collectionof }
            
    pi_app_admin.validator.partner:
       class:      %pi_app_admin.validator.partner.class%
       arguments: [@service_container]
       tags:
            - { name: validator.constraint_validator, alias: pi_app_admin.validator.partner }                  